export const services = [
  // Plumbing Services
  {
    id: "plumb-1",
    title: "Pipe Repair & Installation",
    category: "plumbing",
    price: "₹500-1000",
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Sharma Plumbing Solutions",
    location: "Kothrud, Pune",
    availability: "Available today",
    reviews: 127,
    description:
      "Professional pipe repair and installation services for your home or business in Pune. We fix leaks, replace old pipes, and install new plumbing systems with quality materials and workmanship.",
    href: "/services/plumbing/plumb-1",
    providerId: "prov-1",
  },
  {
    id: "plumb-2",
    title: "Drain Cleaning",
    category: "plumbing",
    price: "₹400-800",
    rating: 4.6,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Sharma Plumbing Co.",
    location: "Aundh, Pune",
    availability: "Available today",
    reviews: 98,
    description:
      "Fast and effective drain cleaning services to fix clogs and improve drainage in Pune homes. We use professional-grade equipment to clear even the most stubborn blockages.",
    href: "/services/plumbing/plumb-2",
    providerId: "prov-1",
  },
  {
    id: "plumb-3",
    title: "Water Heater Installation",
    category: "plumbing",
    price: "₹1200-2000",
    rating: 4.9,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Kumar Plumbing Solutions",
    location: "Viman Nagar, Pune",
    availability: "Available tomorrow",
    reviews: 156,
    description:
      "Expert water heater installation and repair services for Pune residents. We install all types of water heaters including tankless, solar, and traditional storage tank models.",
    href: "/services/plumbing/plumb-3",
    providerId: "prov-5",
  },

  // Electrical Services
  {
    id: "elec-1",
    title: "Electrical Wiring",
    category: "electrical",
    price: "₹600-1200",
    rating: 4.7,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Patel Electrical Services",
    location: "Shivaji Nagar, Pune",
    availability: "Available today",
    reviews: 112,
    description:
      "Complete electrical wiring services for new construction or renovations in Pune. Our licensed electricians ensure safe and code-compliant installations for your home or business.",
    href: "/services/electrical/elec-1",
    providerId: "prov-2",
  },
  {
    id: "elec-2",
    title: "Circuit Breaker Repair",
    category: "electrical",
    price: "₹500-900",
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Singh Electrical Co.",
    location: "Hadapsar, Pune",
    availability: "Available today",
    reviews: 87,
    description:
      "Fast and reliable circuit breaker repair and replacement services in Pune. We diagnose and fix electrical panel issues to keep your home safe and powered.",
    href: "/services/electrical/elec-2",
    providerId: "prov-6",
  },
  {
    id: "elec-3",
    title: "Lighting Installation",
    category: "electrical",
    price: "₹400-800",
    rating: 4.6,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Gupta Electrical Solutions",
    location: "Baner, Pune",
    availability: "Available tomorrow",
    reviews: 76,
    description:
      "Professional lighting installation for indoor and outdoor spaces in Pune homes. We install ceiling fans, chandeliers, recessed lighting, and landscape lighting systems.",
    href: "/services/electrical/elec-3",
    providerId: "prov-7",
  },

  // Carpentry Services
  {
    id: "carp-1",
    title: "Custom Furniture",
    category: "carpentry",
    price: "₹2000-5000",
    rating: 4.9,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Verma Woodworks",
    location: "Koregaon Park, Pune",
    availability: "Available in 2 days",
    reviews: 143,
    description:
      "Custom furniture design and creation tailored to your needs in Pune. We craft beautiful, durable furniture pieces including tables, chairs, beds, and cabinets to your specifications.",
    href: "/services/carpentry/carp-1",
    providerId: "prov-3",
  },
  {
    id: "carp-2",
    title: "Cabinet Installation",
    category: "carpentry",
    price: "₹1500-3000",
    rating: 4.7,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Sharma Carpentry",
    location: "Wakad, Pune",
    availability: "Available tomorrow",
    reviews: 92,
    description:
      "Professional cabinet installation for kitchens and bathrooms in Pune homes. We install pre-manufactured cabinets or create custom solutions for your space.",
    href: "/services/carpentry/carp-2",
    providerId: "prov-8",
  },
  {
    id: "carp-3",
    title: "Door & Window Repair",
    category: "carpentry",
    price: "₹800-1500",
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Joshi Carpentry Services",
    location: "Kondhwa, Pune",
    availability: "Available today",
    reviews: 108,
    description:
      "Expert door and window repair and installation services in Pune. We fix stuck doors, broken frames, and install new doors and windows with proper sealing and finishing.",
    href: "/services/carpentry/carp-3",
    providerId: "prov-9",
  },

  // Cleaning Services
  {
    id: "clean-1",
    title: "Deep House Cleaning",
    category: "cleaning",
    price: "₹1000-2500",
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=300",
    provider: "House Swachh Services",
    location: "Kalyani Nagar, Pune",
    availability: "Available today",
    reviews: 132,
    description:
      "Comprehensive deep cleaning services for your entire home in Pune. Our professional cleaners tackle dirt, dust, and grime in every corner of your home, leaving it spotless and fresh.",
    href: "/services/cleaning/clean-1",
    providerId: "prov-4",
  },
  {
    id: "clean-2",
    title: "Office Cleaning",
    category: "cleaning",
    price: "₹1500-3000",
    rating: 4.7,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Clean Pro Services",
    location: "Hinjewadi, Pune",
    availability: "Available tomorrow",
    reviews: 87,
    description:
      "Professional office cleaning services for businesses of all sizes in Pune. We provide regular maintenance cleaning, deep cleaning, and specialized services for commercial spaces.",
    href: "/services/cleaning/clean-2",
    providerId: "prov-10",
  },
  {
    id: "clean-3",
    title: "Carpet Cleaning",
    category: "cleaning",
    price: "₹600-1200",
    rating: 4.6,
    image: "/placeholder.svg?height=200&width=300",
    provider: "Fresh Cleaning Co.",
    location: "Magarpatta, Pune",
    availability: "Available today",
    reviews: 76,
    description:
      "Deep carpet cleaning to remove stains, dirt, and allergens in Pune homes. We use hot water extraction and eco-friendly cleaning solutions to restore your carpets to like-new condition.",
    href: "/services/cleaning/clean-3",
    providerId: "prov-11",
  },
]

export const providers = [
  {
    id: "prov-1",
    name: "Sharma Plumbing Solutions",
    businessName: "Sharma Plumbing Solutions",
    category: "plumbing",
    rating: 4.8,
    reviews: 127,
    image: "/placeholder.svg?height=100&width=100",
    location: "Kothrud, Pune",
    city: "Pune",
    experience: "10+ years",
    description:
      "Professional plumbing services with over a decade of experience serving Pune residents. We specialize in all types of plumbing repairs, installations, and maintenance.",
    address: "123 Karve Road, Kothrud, Pune, Maharashtra 411038",
    phone: "+91 98765 43210",
    email: "contact@sharmaplumbing.com",
    workingHours: "Mon-Sat: 8:00 AM - 8:00 PM, Sun: 10:00 AM - 4:00 PM",
    services: [
      "Pipe repair and installation",
      "Drain cleaning",
      "Water heater services",
      "Bathroom fixture installation",
      "Leak detection and repair",
    ],
  },
  {
    id: "prov-2",
    name: "Patel Electrical Services",
    businessName: "Patel Electrical Services",
    category: "electrical",
    rating: 4.7,
    reviews: 112,
    image: "/placeholder.svg?height=100&width=100",
    location: "Shivaji Nagar, Pune",
    city: "Pune",
    experience: "8+ years",
    description:
      "Reliable electrical services for residential and commercial needs in Pune. Our licensed electricians provide safe and efficient solutions for all your electrical requirements.",
    address: "45 FC Road, Shivaji Nagar, Pune, Maharashtra 411005",
    phone: "+91 98765 12345",
    email: "info@patelelectrical.com",
    workingHours: "Mon-Sat: 9:00 AM - 7:00 PM, Sun: Closed",
    services: [
      "Electrical wiring",
      "Circuit breaker repair",
      "Lighting installation",
      "Electrical panel upgrades",
      "Ceiling fan installation",
    ],
  },
  {
    id: "prov-3",
    name: "Verma Woodworks",
    businessName: "Verma Woodworks",
    category: "carpentry",
    rating: 4.9,
    reviews: 143,
    image: "/placeholder.svg?height=100&width=100",
    location: "Koregaon Park, Pune",
    city: "Pune",
    experience: "15+ years",
    description:
      "Expert carpentry and woodworking services for custom projects in Pune. We create beautiful, functional wooden furniture and fixtures tailored to your specific needs and preferences.",
    address: "78 North Main Road, Koregaon Park, Pune, Maharashtra 411001",
    phone: "+91 98765 67890",
    email: "contact@vermawoodworks.com",
    workingHours: "Mon-Sat: 10:00 AM - 6:00 PM, Sun: By appointment only",
    services: [
      "Custom furniture design",
      "Cabinet installation",
      "Door and window repair",
      "Wood flooring installation",
      "Custom shelving and storage solutions",
    ],
  },
  {
    id: "prov-4",
    name: "House Swachh Services",
    businessName: "House Swachh Services",
    category: "cleaning",
    rating: 4.8,
    reviews: 132,
    image: "/placeholder.svg?height=100&width=100",
    location: "Kalyani Nagar, Pune",
    city: "Pune",
    experience: "7+ years",
    description:
      "Professional cleaning services for homes and offices throughout Pune. Our trained cleaning staff use eco-friendly products and efficient techniques to deliver exceptional results.",
    address: "32 Kalyani Nagar, Pune, Maharashtra 411006",
    phone: "+91 98765 09876",
    email: "info@houseswachh.com",
    workingHours: "Mon-Sun: 8:00 AM - 8:00 PM",
    services: [
      "Deep house cleaning",
      "Office cleaning",
      "Carpet cleaning",
      "Post-construction cleaning",
      "Move-in/move-out cleaning",
    ],
  },
  {
    id: "prov-5",
    name: "Kumar Plumbing Solutions",
    businessName: "Kumar Plumbing Solutions",
    category: "plumbing",
    rating: 4.9,
    reviews: 156,
    image: "/placeholder.svg?height=100&width=100",
    location: "Viman Nagar, Pune",
    city: "Pune",
    experience: "12+ years",
    description:
      "Expert plumbing services for residential and commercial properties in Pune. We provide prompt, reliable service for all your plumbing needs at competitive rates.",
    address: "56 Phoenix Road, Viman Nagar, Pune, Maharashtra 411014",
    phone: "+91 98765 23456",
    email: "service@kumarplumbing.com",
    workingHours: "Mon-Sat: 7:00 AM - 9:00 PM, Sun: 9:00 AM - 5:00 PM",
    services: [
      "Water heater installation",
      "Sewer line repair",
      "Bathroom remodeling",
      "Water filtration systems",
      "Emergency plumbing services",
    ],
  },
  {
    id: "prov-6",
    name: "Singh Electrical Co.",
    businessName: "Singh Electrical Co.",
    category: "electrical",
    rating: 4.8,
    reviews: 87,
    image: "/placeholder.svg?height=100&width=100",
    location: "Hadapsar, Pune",
    city: "Pune",
    experience: "9+ years",
    description:
      "Trusted electrical contractors serving Pune with quality workmanship and attention to detail. We handle projects of all sizes with a focus on safety and customer satisfaction.",
    address: "123 Solapur Road, Hadapsar, Pune, Maharashtra 411028",
    phone: "+91 98765 34567",
    email: "contact@singhelectrical.com",
    workingHours: "Mon-Sat: 8:30 AM - 7:30 PM, Sun: Closed",
    services: [
      "Circuit breaker repair",
      "Electrical troubleshooting",
      "Home rewiring",
      "Generator installation",
      "Smart home wiring",
    ],
  },
  {
    id: "prov-7",
    name: "Gupta Electrical Solutions",
    businessName: "Gupta Electrical Solutions",
    category: "electrical",
    rating: 4.6,
    reviews: 76,
    image: "/placeholder.svg?height=100&width=100",
    location: "Baner, Pune",
    city: "Pune",
    experience: "6+ years",
    description:
      "Professional electrical services for homes and businesses in Pune. We provide energy-efficient solutions and quality installations at affordable prices.",
    address: "45 Baner Road, Baner, Pune, Maharashtra 411045",
    phone: "+91 98765 45678",
    email: "info@guptaelectrical.com",
    workingHours: "Mon-Sat: 9:00 AM - 6:00 PM, Sun: By appointment only",
    services: [
      "Lighting installation",
      "Electrical safety inspections",
      "Outlet and switch installation",
      "Surge protection",
      "Landscape lighting",
    ],
  },
  {
    id: "prov-8",
    name: "Sharma Carpentry",
    businessName: "Sharma Carpentry",
    category: "carpentry",
    rating: 4.7,
    reviews: 92,
    image: "/placeholder.svg?height=100&width=100",
    location: "Wakad, Pune",
    city: "Pune",
    experience: "11+ years",
    description:
      "Quality carpentry services for residential and commercial clients in Pune. We combine traditional craftsmanship with modern techniques to deliver outstanding results.",
    address: "78 Wakad Road, Wakad, Pune, Maharashtra 411057",
    phone: "+91 98765 56789",
    email: "contact@sharmacarpentry.com",
    workingHours: "Mon-Sat: 9:00 AM - 7:00 PM, Sun: Closed",
    services: [
      "Cabinet installation",
      "Furniture repair",
      "Custom built-ins",
      "Deck construction",
      "Trim and molding installation",
    ],
  },
  {
    id: "prov-9",
    name: "Joshi Carpentry Services",
    businessName: "Joshi Carpentry Services",
    category: "carpentry",
    rating: 4.8,
    reviews: 108,
    image: "/placeholder.svg?height=100&width=100",
    location: "Kondhwa, Pune",
    city: "Pune",
    experience: "14+ years",
    description:
      "Skilled carpentry services for all your woodworking needs in Pune. We specialize in custom solutions that blend functionality with aesthetic appeal.",
    address: "34 Kondhwa Road, Kondhwa, Pune, Maharashtra 411048",
    phone: "+91 98765 67890",
    email: "info@joshicarpentry.com",
    workingHours: "Mon-Sat: 8:00 AM - 6:00 PM, Sun: Closed",
    services: [
      "Door and window repair",
      "Staircase construction",
      "Wood flooring",
      "Kitchen remodeling",
      "Custom woodworking",
    ],
  },
  {
    id: "prov-10",
    name: "Clean Pro Services",
    businessName: "Clean Pro Services",
    category: "cleaning",
    rating: 4.7,
    reviews: 87,
    image: "/placeholder.svg?height=100&width=100",
    location: "Hinjewadi, Pune",
    city: "Pune",
    experience: "8+ years",
    description:
      "Professional cleaning services for commercial and residential properties in Pune. We deliver consistent, high-quality cleaning results that exceed expectations.",
    address: "56 Hinjewadi Phase 1, Pune, Maharashtra 411057",
    phone: "+91 98765 78901",
    email: "service@cleanpro.com",
    workingHours: "Mon-Sun: 7:00 AM - 9:00 PM",
    services: ["Office cleaning", "Commercial cleaning", "Janitorial services", "Floor maintenance", "Window cleaning"],
  },
  {
    id: "prov-11",
    name: "Fresh Cleaning Co.",
    businessName: "Fresh Cleaning Co.",
    category: "cleaning",
    rating: 4.6,
    reviews: 76,
    image: "/placeholder.svg?height=100&width=100",
    location: "Magarpatta, Pune",
    city: "Pune",
    experience: "5+ years",
    description:
      "Reliable cleaning services for homes and businesses in Pune. We use advanced cleaning techniques and eco-friendly products to create healthier indoor environments.",
    address: "23 Magarpatta City, Pune, Maharashtra 411028",
    phone: "+91 98765 89012",
    email: "info@freshcleaning.com",
    workingHours: "Mon-Sat: 8:00 AM - 8:00 PM, Sun: 9:00 AM - 5:00 PM",
    services: [
      "Carpet cleaning",
      "Upholstery cleaning",
      "Air duct cleaning",
      "Tile and grout cleaning",
      "Sanitization services",
    ],
  },
]

